apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:  # podの概要
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate # .spec.strategy.type==Recreateと指定されているとき、既存の全てのPodは新しいPodが作成される前に削除されます。
  template: # podのtemplate
    metadata:
      labels:
        app: influxdb # metadata.labels.appと合わせたほうがいいかも
    spec:
      containers:
      - image: myinfluxdb
        imagePullPolicy: Never
        name: influxdb
        livenessProbe:
          exec:
            command: ["sh", "./livenessprobe.sh"]
          initialDelaySeconds: 30 # コンテナ起動してから確認を開始するまで
          timeoutSeconds: 10 # timeoutを判定する秒数 default:1
          periodSeconds: 30 # proveの間隔 default : 10
        ports:
        - containerPort: 8086 # 8083はv1.3.0で終了。これは1.8.3
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
  - port: 8086
  selector:
    app: influxdb
  clusterIP: None
