FROM basecamp

COPY start.sh /start.sh
COPY influxdb.conf /etc/influxdb.conf
COPY telegraf.conf /etc/telegraf.conf
COPY livenessprobe.sh /livenessprobe.sh

RUN mkdir -p /etc/ssl
RUN cp /etc/nginx/ssl/ft_service.crt /etc/ssl/ft_service.crt
RUN cp /etc/nginx/ssl/ft_service.key /etc/ssl/ft_service.key
RUN chmod -R 777 /etc/ssl

EXPOSE 8086
CMD ["/start.sh"]