# https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
# hostpath use only test single node. https://qiita.com/sotoiwa/items/09d2f43a35025e7be782#hostpathpersistentvolume
# minikube内の保存先かも mount先ではない。
  hostPath:
    path: "/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi