# https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-metallb # このラベルは全部のpodにつけられる
  name: nginx-metallb  # deploymentの名前
spec:  # podの概要
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metallb
  template: # podのtemplate
    metadata:
      labels:
        app: nginx-metallb # metadata.labels.appと合わせたほうがいいかも
    spec:
      containers:
      - image: mynginx
        imagePullPolicy: Never
        name: nginx-metallb
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metallb
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  selector: # DeploymentのPodのlabelとセット
    app: nginx-metallb
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
