# https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx # このラベルは全部のpodにつけられる
  name: nginx  # deploymentの名前
spec:  # podの概要
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: # podのtemplate
    metadata:
      labels:
        app: nginx # metadata.labels.appと合わせたほうがいいかも
    spec:
      containers:
      - image: mynginx
        imagePullPolicy: Never
        name: nginx
        livenessProbe:
          exec:
            command: ["sh", "./livenessprobe.sh"]
          initialDelaySeconds: 20 # コンテナ起動してから確認を開始するまで
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer
  selector: # DeploymentのPodのlabelとセット
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
