FROM basecamp

COPY vsftpd.conf start.sh ./

RUN adduser -D ftp-user \
  && echo 'ftp-user:ftp-user' | chpasswd

# FTPで接続したときにデフォルトでたどり着くディレクトリ
RUN mkdir -p /etc/ftps/ftp_admin && \
	adduser --home=/etc/ftps/ftp_admin -D ftp_admin && \
	echo "ftp_admin:01010" | chpasswd

RUN mv vsftpd.conf /etc/vsftpd/ && \
	echo "ftp_admin" >> /etc/vsftpd/vsftpd.userlist

EXPOSE 20 21 21009-21011
RUN chmod -R 777 /tmp /var

WORKDIR /

CMD [ "/start.sh" ]
