apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
#       - image: phpmyadmin
      - image: mypma
        imagePullPolicy: Never
        name: phpmyadmin

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
#  annotations:
#    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
