apiVersion: v1
kind: Service
metadata:
  name: my-first-service
spec:
  selector:
    component: nginx
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  type: NodePort